name: Update Registry

on:
  push:
    branches: [main]
    paths:
      - 'subagents/**'
      - 'commands/**'
      - 'scripts/generate-registry.js'
      - 'scripts/fetch-docker-mcp.js'
  workflow_dispatch:

jobs:
  update-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Docker (optional for Docker MCP)
        uses: docker/setup-buildx-action@v3
        continue-on-error: true
          
      - name: Install gray-matter
        run: npm install gray-matter
        
      - name: Generate registry.json
        env:
          CI: 'true'
        run: node scripts/generate-registry.js
        
      - name: Validate registry generation
        run: |
          echo "Registry generation completed successfully"
          echo "Note: registry.json is generated at build time and not committed to git"
          
      - name: Trigger Vercel Deployment
        if: success()
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            echo "Triggering Vercel deployment with updated registry..."
            curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
            echo "Deployment triggered successfully"
          else
            echo "VERCEL_DEPLOY_HOOK secret not configured, skipping deployment trigger"
          fi
